2017-01: Retroactive Updates
* Disabled gputest
  * The package is failing to install.

* Now using Midori GTK3 build
  * GTK2 was pulled from main repos for security reasons

* Removed warnings about missing UFD
  * For use with live sessions

* Wallpaper updated for live sessions
  * Wallpaper is now set at startup
  * Checks for UFD source but defaults to included file
  * Bugfix: Wallpaper is now set for multiple monitor/workspace setups

* Disabled choose-mirror service

* Better permission handling
  * build-wk now checks if running as root
  * build-wk now sets permissions before calling build.sh
    * Should prevent build failues as build.sh expects files to be owned by root
    * build-wk sets ownership back to builduser.builduser during cleanup

* Better menu for HW-Diags
  * The script now returns to the menu after running a selection
    * Unless the mode was set directly by passing a valid argument
    * NOTE: This allows for easier use in CLI mode

* Add delay before removing /media/wktech

* Adjusted TMP_DIR in build-wk

* Fixed path to custom repo

* Trimming the fat
  * hostname / hosts now configured by customize_airootfs.sh
  * removed files from etc that were at default settings
  * removed grml zsh config since oh-my-zsh/lean is used

* Defined a LOG_DIR for build-wk

* Introducing libinput
  * Switched to libinput over synaptics as it has been deprecated.
    * Should restore touchpad functionality going forward.
* Full mount path SHOULD now be displayed for mount-all-volumes.

* Added CLI Screensavers

* diag-network works now
  * network connection tests now passes all ipv4 private ip ranges
    * 10.0.0.0/8, 172.16.0.0/12, & 192.168.0.0/24
    * need to add ipv6 at some point
  * hw-diag menu flow adjusted

* New hostname and more bugfixes
  * hostname switched to wk-arch
  * ufw package is now installed
  * adjusted upload section of hw-diags

* Added alias for start-wifi

* Booting to CLI mode will autologin wktech
  * When booting to the CLI the motd shows some avail commands
  * Adjusted HW-Diags menu for use in CLI mode

diff --git a/archlive/airootfs/usr/local/bin/connect-to-network b/archlive/airootfs/usr/local/bin/connect-to-network
--- a/archlive/airootfs/usr/local/bin/connect-to-network
+++ b/archlive/airootfs/usr/local/bin/connect-to-network
@@ -11,20 +11,21 @@ die () {
     exit 1
 }
 
+function test_connection() {
+    if ip a | grep -Eq '(10.[0-9]+|172.(1[6-9]|2[0-9]|3[0-1]).[0-9]+|192.168).[0-9]+.[0-9]+'; then
+        return 0
+    else
+        return 1
+    fi
+}
+
 # Load settings
 if [[ -f "/run/archiso/bootmnt/config/arch.conf" ]]; then
     source "/run/archiso/bootmnt/config/arch.conf" || \
-        die "ERROR: ARCH_WK media may be damaged. Please reboot or try another UFD"
+        die "ERROR: WK_ARCH media may be damaged. Please reboot or try another UFD"
 else
     source "/usr/local/bin/arch.conf" || \
-        die "ERROR: ARCH_WK media may be damaged. Please reboot or try another UFD"
-    echo -n "ERROR: Settings file on ARCH_WK media missing. Using build version for now"
-    sleep 1s
-    echo -n "."
-    sleep 1s
-    echo -n "."
-    sleep 1s
-    echo "."
+        die "ERROR: WK_ARCH media may be damaged. Please reboot or try another UFD"
 fi
 
 # Init
@@ -32,7 +33,7 @@ WIFI_SSID="${WIFI_SSID}"
 WIFI_PASS="${WIFI_PASS}"
 
 # Connect to network
-if ! ip a | grep -Eq '(192.168|10.[0-9]+).[0-9]+.[0-9]+'; then
+if ! test_connection; then
     # LAN
     if ! ip l | grep -Eq '[0-9]+: +en'; then
         ## Reload the tg3/broadcom driver (known fix for some Dell systems)
@@ -46,13 +47,18 @@ if ! ip a | grep -Eq '(192.168|10.[0-9]+).[0-9]+.[0-9]+'; then
     # WiFi
     if ip l | grep -Eq '[0-9]+: +wl'; then
         ## Skip if we're already connected (i.e. the code above worked)
-        if ! ip a | grep -Eq '(192.168|10.[0-9]+).[0-9]+.[0-9]+'; then
+        if ! test_connection; then
             echo "Attempting to connect to ${WIFI_SSID}..."
-            netctl start wireless
+            sudo start-wifi
             sleep 5s
         fi
     fi
 fi
 
 # Done
-exit 0
+if test_connection; then
+    exit 0
+else
+    exit 1
+fi
+
