2016-08: Retroactive Updates
* Added arch.conf file which is loaded from the UFD
  * Allows configuration without rebuilding the ISO
* Added connect-to-network script that uses arch.conf
  * Available for manual execution from the command line
  * Used by mount-backup-shares
* Added hardinfo with Conky hint and keyboard shortcut (Super+i)
* Avoid deleting a newly created iso right after building
* Conky
  * Settings can now be stored on the UFD
  * Transparancy fixed
* mount-all-volumes doesn't print the mountpoint for ARCH_HH
* NetworkManager should no longer hold up the boot time
* Prime95
  * Adjusted default length due to the summer heat
  * Fixed bug where hw-diags would let it run forever
* Removed extra themes to try and reduce the overall size
* Switching to nodm over lightdm

diff --git a/archlive/airootfs/usr/local/bin/hw-diags-inner b/archlive/airootfs/usr/local/bin/hw-diags-inner
--- a/archlive/airootfs/usr/local/bin/hw-diags-inner
+++ b/archlive/airootfs/usr/local/bin/hw-diags-inner
@@ -2,8 +2,30 @@
 #
 ## WK HW Diagnostics - Main script
 
+die () {
+    echo "$0:" "$@" >&2
+    exit 1
+}
+
+# Load settings
+if [[ -f "/run/archiso/bootmnt/arch/arch.conf" ]]; then
+    source "/run/archiso/bootmnt/arch/arch.conf" || \
+        die "ERROR: ARCH_WK media may be damaged. Please reboot or try another UFD"
+else
+    source "/usr/local/bin/arch.conf" || \
+        die "ERROR: ARCH_WK media may be damaged. Please reboot or try another UFD"
+    echo -n "ERROR: Settings file on ARCH_WK media missing. Using build version for now"
+    sleep 1s
+    echo -n "."
+    sleep 1s
+    echo -n "."
+    sleep 1s
+    echo "."
+fi
+
 # Get TICKET
-SKIP_UPLOAD=""
+## Inital SKIP_UPLOAD value loaded from arch.conf
+SKIP_UPLOAD="${SKIP_UPLOAD}"
 TICKET=""
 while [[ "$TICKET" == "" ]]; do
     if [[ "$1" == "foh" ]]; then
@@ -22,16 +44,16 @@ while [[ "$TICKET" == "" ]]; do
 done
 
 # Init
+## Tautologies left to show which settings are coming from arch.conf
 DIAG_DATE="$(date "+%F_%H%M")"
 DIAG_SERVER_AVAIL="False"
-DIAG_SERVER="10.0.0.10"
-DIAG_DEST="/srv/Diagnostics/${TICKET}/${DIAG_DATE}"
-DIAG_USER="wkdiag"
+DIAG_SERVER="${DIAG_SERVER}"
+DIAG_DEST="${DIAG_DEST}/${TICKET}/${DIAG_DATE}"
+DIAG_USER="${DIAG_USER}"
 TMP_DIR="$(mktemp -d)"
 ERRORS="False"
-ERROR_IMG="$TMP_DIR/error.jpg"
-PASSED_IMG="$TMP_DIR/passed.jpg"
 TEST_CPU="False"
+TEST_CPU_LENGTH="${TEST_CPU_LENGTH}"
 TEST_OVER="False"
 TEST_SMART="False"
 TEST_BADBLOCKS="False"
@@ -51,30 +73,10 @@ done
 # Handle testing runs
 if [[ "$SKIP_UPLOAD" != "True" ]]; then
     # Connect to network
-    if ! ip a | grep -q '192.168.1'; then
-        # LAN
-        if ! ip l | grep -Eq '[0-9]+: +en'; then
-            ## Reload the tg3/broadcom driver (known fix for some Dell systems)
-            echo "No wired network adapters found; reloading drivers..."
-            sudo modprobe -r tg3
-            sudo modprobe broadcom
-            sudo modprobe tg3
-            sleep 5s
-        fi
-        
-        # WiFi
-        if ip l | grep -Eq '[0-9]+: +wl'; then
-            ## Skip if we're already connected (e.g. the code above worked)
-            if ! ip a | grep -q '192.168.1'; then
-                echo "Attempting to connect to SomeWiFi..."
-                nmcli dev wifi con "SomeWiFi" password "Abracadabra"
-                sleep 5s
-            fi
-        fi
-    fi
+    connect-to-network
 
     # Test connection to DIAG_SERVER
-    if ip a | grep -q '192.168.1' && \
+    if ip a | grep -Eq '(192.168|10.[0-9]+).[0-9]+.[0-9]+' && \
     ping -c 1 -q $DIAG_SERVER >/dev/null 2>&1; then
         DIAG_SERVER_AVAIL="True"
         ssh $DIAG_USER@$DIAG_SERVER mkdir -p "$DIAG_DEST"
@@ -250,8 +252,8 @@ if [[ "$TEST_CPU" == "True" ]]; then
     CPU_ERRORS="False"
     cpu_result="Working"
     update_progress
-    (sleep 10m && killall -s INT "mprime" >>/dev/null 2>&1) &
-    (sleep 10m && killall "hw-diags-sensors" >>/dev/null 2>&1) &
+    (sleep ${TEST_CPU_LENGTH}m && killall -s INT "mprime" >>/dev/null 2>&1) &
+    (sleep ${TEST_CPU_LENGTH}m && killall "hw-diags-sensors" >>/dev/null 2>&1) &
     tmux split-window -d -v -l 10 "hw-diags-prime95 $TMP_DIR"
     hw-diags-sensors "$TMP_DIR" 2>/dev/null
     sleep 1s
diff --git a/archlive/airootfs/usr/local/bin/mount-all-volumes b/archlive/airootfs/usr/local/bin/mount-all-volumes
--- a/archlive/airootfs/usr/local/bin/mount-all-volumes
+++ b/archlive/airootfs/usr/local/bin/mount-all-volumes
@@ -2,9 +2,28 @@
 #
 ## Mount all volumes read-only
 
+# Fix issue where first device is mounted under /media/wktech/
+TMP_FILE=$(mktemp)
+dd bs=1K count=64 if=/dev/zero of="$TMP_FILE" >/dev/null 2>&1
+mkfs.msdos "$TMP_FILE" >/dev/null 2>&1
+udevil mount -o ro "$TMP_FILE" >/dev/null 2>&1
+udevil umount "$TMP_FILE" >/dev/null 2>&1
+
+# Mount all volumes
 echo "Mounting all volumes"
 regex="/dev/((h|s)d[a-z]|md)[0-9]+"
-for v in $(inxi -Do | grep -E "$regex" | sed -r "s#.*($regex).*#\1#" | sort); do
-    udevil mount -o ro $v
+for volume in $(inxi -Dopxx | grep -E "$regex" | sed -r "s#.*($regex).*#\1#" | sort); do
+    if grep -q "$volume" /proc/mounts; then
+        if ! mount | grep "/run/archiso/bootmnt" | grep -q "$volume"; then
+            # Show what's already mounted except the ARCH_WK boot device
+            echo "$volume: (Already) mounted at $(mount | grep "$volume" | awk '{print $3}') ($(df -h "$volume" | tail -1 | awk '{print $3, $4}' | sed -r 's/(K|M|G|T|) (.*[0-9])(K|M|G|T|)$/ \1b used, \2 \3b free/'))"
+        fi
+    else
+        if udevil mount -o ro $volume >/dev/null 2>&1; then
+            echo "$volume: Mounted at $(mount | grep "$volume" | awk '{print $3}') ($(df -h "$volume" | tail -1 | awk '{print $3, $4}' | sed -r 's/(K|M|G|T|) (.*[0-9])(K|M|G|T|)$/ \1b used, \2 \3b free/'))"
+        else
+            echo "$volume: Failed to mount"
+        fi
+    fi
 done
 echo "Done."
